name: Build & Sign Android AAB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Decode keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > my-release-key.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build signed AAB
        run: ./gradlew bundleRelease \
          -Pandroid.injected.signing.store.file=my-release-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: app/build/outputs/bundle/release/app-release.aab
